### PR TITLE
Merge maehr/awesome-digital-history/wiki

### PR DESCRIPTION
**Pull request by maehr**
As discussed in <https://github.com/dh-tech/awesome-dhtools/issues/11> I merged <https://github.com/maehr/awesome-digital-history/wiki> into <https://github.com/maehr/awesome-dhtools>

Please @pacian checkout <https://github.com/maehr/awesome-dhtools>

### CODE REVIEW

**Comment by maehr** [comment]
Hello all. I have not received any response from any maintainer. What do you think @diegosiqueir4 about my PR?
Thank you very much and best regards
Moritz

**Comment by jdamerow** [comment]
Hi @maehr, this is great! Sorry for being slow, we just don't have a formal process for PRs yet. Let me get someone else to also have a look at it and then it should be good to go.

**Review by jdamerow — APPROVED** [review]

**Comment by maehr** [comment]
@jdamerow thanks for approving my PR.
Cheers
Moritz

**Comment by maehr** [comment]
@jdamerow Hi there
Do you plan to merge my PR?
Best, moritz

**Comment by diegosiqueir4** [comment]
> Hello all. I have not received any response from any maintainer. What do you think @diegosiqueir4 about my PR? Thank you very much and best regards Moritz

Hello @maehr,
sorry for the delay in responding. I was on vacation and only now was able to process all my messages. Glad to see that PR has already been merged with master. Keep up the good work!

**Pull request merged**
