### PR TITLE
Add Awesome Digital History in Other DH Tools Repositories

### PR DESCRIPTION
**Pull request by diegosiqueir4**
A curated list of awesome things related to digital history.

"This collection brings together the best publicly accessible tools, source collections and platforms for digital history and related disciplines."

### CODE REVIEW

**Comment by diegosiqueir4** [comment]
Since this pull request is still open it was not possible to separate the contributions. 

I suggest adding #dariahTeach in the User Guides section as well.

**Comment by yoannspace** [comment]
Thanks, I would be ok with it.

2 suggestions:
- maybe also add [DARIAH campus](https://campus.dariah.eu)
- rename `User Guides` with `User Guides & Training Materials`

**Comment by diegosiqueir4** [comment]
Thanks for the review, @yoannspace.
I just incorporated your suggestions.

**Comment by jdamerow** [comment]
@diegosiqueir4 thanks for keep adding to this! And sorry for the long delay!

**Comment by diegosiqueir4** [comment]
@jdamerow , no worries. I am happy to contribute :)

**Pull request merged**
